services:
  app:
    image: dot:v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dot-app-v1
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env.example
    volumes:
      - ./:/var/www/html
      # - ./bootstrap/cache:/var/www/html/bootstrap/cache
      # - ./storage:/var/www/html/storage
    entrypoint: ["/var/www/html/docker-app-entrypoint.sh"]
    networks:
      - dot-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: dot-nginx-v1
    restart: unless-stopped
    ports:
      - "8092:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
      - ./docker-nginx-entrypoint.sh:/var/www/html/docker-nginx-entrypoint.sh
    depends_on:
      - app
    entrypoint: ["/var/www/html/docker-nginx-entrypoint.sh"]
    networks:
      - dot-network


networks:
  dot-network:
    driver: bridge
